# Generated by Django 5.2.14 on 2026-05-27 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_lit', models.CharField(max_length=10)),
                ('est_disponible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Lit',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100)),
                ('adresse', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HospitalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='clinical.building')),
            ],
            options={
                'verbose_name': 'Service hospitalier',
                'verbose_name_plural': 'Services hospitaliers',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('numero_dossier', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('A', 'Autre')], max_length=1)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField(blank=True)),
                ('groupe_sanguin', models.CharField(blank=True, max_length=5)),
                ('consentement_traitement', models.BooleanField(default=False)),
                ('consentement_date', models.DateTimeField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=200)),
                ('fichier', models.FileField(upload_to='documents/%Y/%m/')),
                ('mime_type', models.CharField(max_length=100)),
                ('taille_octets', models.PositiveIntegerField()),
                ('signe_electroniquement', models.BooleanField(default=False)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clinical.patient')),
            ],
            options={
                'verbose_name': 'Document médical',
            },
        ),
        migrations.CreateModel(
            name='Hospitalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('date_entree', models.DateTimeField()),
                ('date_sortie_prevue', models.DateField()),
                ('date_sortie_effective', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('ACTIVE', 'En cours'), ('SORTIE', 'Sorti(e)'), ('TRANSFERT', 'Transfert en cours')], default='ACTIVE', max_length=15)),
                ('motif_admission', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('lit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospitalisations', to='clinical.bed')),
                ('medecin_referent', models.ForeignKey(limit_choices_to={'role': 'MEDECIN'}, on_delete=django.db.models.deletion.PROTECT, related_name='hospitalisations_referent', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospitalisations', to='clinical.patient')),
            ],
            options={
                'verbose_name': 'Hospitalisation',
                'ordering': ['-date_entree'],
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('date_consultation', models.DateTimeField(auto_now_add=True)),
                ('diagnostic_cim10', models.CharField(help_text='Code CIM-10', max_length=10)),
                ('diagnostic_libelle', models.CharField(max_length=255)),
                ('notes_cliniques', models.TextField(blank=True)),
                ('validee', models.BooleanField(default=False)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('medecin', models.ForeignKey(limit_choices_to={'role': 'MEDECIN'}, on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to=settings.AUTH_USER_MODEL)),
                ('hospitalisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='clinical.hospitalization')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to='clinical.patient')),
            ],
            options={
                'ordering': ['-date_consultation'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('medicament_nom', models.CharField(max_length=200)),
                ('posologie', models.CharField(max_length=255)),
                ('duree_jours', models.PositiveSmallIntegerField()),
                ('instructions', models.TextField(blank=True)),
                ('validee', models.BooleanField(default=False)),
                ('verrouillee', models.BooleanField(default=False)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='clinical.consultation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NursingCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('planifie_a', models.DateTimeField()),
                ('realise_a', models.DateTimeField(blank=True, null=True)),
                ('dose_omise', models.BooleanField(default=False)),
                ('hospitalisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soins', to='clinical.hospitalization')),
                ('infirmier', models.ForeignKey(limit_choices_to={'role': 'INFIRMIER'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soins', to='clinical.prescription')),
            ],
            options={
                'verbose_name': 'Soin infirmier',
                'ordering': ['planifie_a'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=20)),
                ('capacite', models.PositiveSmallIntegerField(default=1)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chambres', to='clinical.hospitalservice')),
            ],
            options={
                'verbose_name': 'Chambre',
                'unique_together': {('service', 'numero')},
            },
        ),
        migrations.AddField(
            model_name='bed',
            name='chambre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lits', to='clinical.room'),
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('tension_systolique', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tension_diastolique', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('frequence_cardiaque', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('saturation_o2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('date_prise', models.DateTimeField(auto_now_add=True)),
                ('hospitalisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constantes', to='clinical.hospitalization')),
                ('infirmier', models.ForeignKey(limit_choices_to={'role': 'INFIRMIER'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_prise'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together={('chambre', 'numero_lit')},
        ),
    ]
