# Generated by Django 5.2.14 on 2026-06-12 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_appointment_conversation_chatmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientCardToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartes_qr', to='clinical.patient')),
            ],
            options={
                'verbose_name': 'Carte patient QR',
                'ordering': ['-created_at'],
            },
        ),
    ]
