# Generated by Django 5.2.14 on 2026-06-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0003_patient_card_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcardtoken',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='cartes_patient/%Y/%m/'),
        ),
    ]
