# Generated by Django 5.2.14 on 2026-06-12 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('clinical', '0002_appointment_conversation_chatmessage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='numero_mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='operateur',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='statut',
            field=models.CharField(choices=[('VALIDE', 'Validé'), ('EN_ATTENTE', 'En attente'), ('REFUSE', 'Refusé')], default='VALIDE', max_length=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='encaisse_par',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['COMPTABLE', 'ADMIN', 'RECEPTIONNISTE']}, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='mode',
            field=models.CharField(choices=[('ESPECES', 'Espèces'), ('CARTE', 'Carte'), ('VIREMENT', 'Virement'), ('CHEQUE', 'Chèque'), ('MTN_MOMO', 'MTN Mobile Money'), ('AIRTEL_MONEY', 'Airtel Money')], max_length=30),
        ),
        migrations.CreateModel(
            name='MobileMoneyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_mobile', models.CharField(max_length=20)),
                ('operateur', models.CharField(max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(max_length=40, unique=True)),
                ('statut', models.CharField(choices=[('INITIE', 'Initié'), ('EN_ATTENTE_CONFIRMATION', 'En attente confirmation téléphone'), ('CONFIRME', 'Confirmé'), ('REFUSE', 'Refusé'), ('EXPIRE', 'Expiré')], default='INITIE', max_length=30)),
                ('message_operateur', models.TextField(blank=True)),
                ('expire_le', models.DateTimeField()),
                ('confirme_le', models.DateTimeField(blank=True, null=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_mobile', to='billing.invoice')),
                ('paiement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_mobile', to='billing.payment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements_mobile', to='clinical.patient')),
            ],
            options={
                'verbose_name': 'Transaction Mobile Money',
                'ordering': ['-created_at'],
            },
        ),
    ]
