# Generated by Django 5.2.14 on 2026-06-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_mobile_money_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilemoneytransaction',
            name='approuve_telephone_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobilemoneytransaction',
            name='code_push',
            field=models.CharField(blank=True, help_text='Code SMS / notification opérateur', max_length=6),
        ),
    ]
