# Generated by Django 5.2.14 on 2026-06-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom_etablissement', models.CharField(default='SGHL — Centre Hospitalier', max_length=200)),
                ('adresse', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('horaires', models.TextField(blank=True, help_text="Horaires d'ouverture")),
                ('urgences_telephone', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('site_web', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Informations établissement',
                'verbose_name_plural': 'Informations établissement',
            },
        ),
    ]
