# Generated by Django 5.2.14 on 2026-06-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_hospitalinfo_geo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalinfo',
            name='urgences_telephone',
            field=models.CharField(blank=True, default='+242 066967236', max_length=30),
        ),
    ]
