# Generated by Django 5.2.14 on 2026-05-27 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=200)),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delai_heures', models.PositiveSmallIntegerField(default=24)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('COMMANDE', 'Commandé'), ('PRELEVEMENT', 'Prélèvement effectué'), ('AFFECTATION', 'Affecté au labo'), ('SAISIE', 'Résultats saisis'), ('VALIDATION', 'En attente validation'), ('PUBLIE', 'Publié'), ('ANNULE', 'Annulé')], default='COMMANDE', max_length=15)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('date_prelevement', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('hospitalisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens_lab', to='clinical.hospitalization')),
                ('medecin_prescripteur', models.ForeignKey(limit_choices_to={'role': 'MEDECIN'}, on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions_lab', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examens_lab', to='clinical.patient')),
                ('technicien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prelevements_lab', to=settings.AUTH_USER_MODEL)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laboratory.labtestcatalog')),
            ],
            options={
                'verbose_name': 'Commande laboratoire',
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valeur', models.TextField()),
                ('unite', models.CharField(blank=True, max_length=30)),
                ('valeur_reference', models.CharField(blank=True, max_length=100)),
                ('commentaire', models.TextField(blank=True)),
                ('valide', models.BooleanField(default=False)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('rapport_pdf', models.FileField(blank=True, upload_to='rapports_lab/%Y/%m/')),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultat', to='laboratory.laborder')),
                ('saisi_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saisies_lab', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, limit_choices_to={'role': 'BIOLOGISTE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations_lab', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabResultAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ancienne_valeur', models.TextField()),
                ('nouvelle_valeur', models.TextField()),
                ('raison', models.TextField(blank=True)),
                ('modifie_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('resultat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='laboratory.labresult')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
