# Generated by Django 5.2.14 on 2026-05-27 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('forme', models.CharField(blank=True, max_length=50)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seuil_alerte', models.PositiveIntegerField(default=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_lot', models.CharField(max_length=50)),
                ('quantite', models.PositiveIntegerField()),
                ('date_peremption', models.DateField()),
                ('emplacement', models.CharField(blank=True, max_length=50)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='pharmacy.medication')),
            ],
            options={
                'verbose_name': 'Lot de stock',
                'unique_together': {('medicament', 'numero_lot')},
            },
        ),
        migrations.CreateModel(
            name='Dispensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantite', models.PositiveIntegerField()),
                ('validee', models.BooleanField(default=False)),
                ('pharmacien', models.ForeignKey(limit_choices_to={'role': 'PHARMACIEN'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispensations', to='clinical.prescription')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy.stocklot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('AJUSTEMENT', 'Ajustement')], max_length=12)),
                ('quantite', models.PositiveIntegerField()),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('effectue_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='pharmacy.stocklot')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'ordering': ['-created_at'],
            },
        ),
    ]
