# Generated by Django 5.2.14 on 2026-06-12 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_appointment_conversation_chatmessage_and_more'),
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='categorie',
            field=models.CharField(choices=[('ANTALGIQUES', 'Antalgiques & antipyrétiques'), ('ANTIBIOTIQUES', 'Antibiotiques'), ('CARDIO', 'Cardiovasculaire'), ('DIABETE', 'Diabète'), ('RESPIRATOIRE', 'Respiratoire'), ('GASTRO', 'Gastro-entérologie'), ('DERMATO', 'Dermatologie'), ('VITAMINES', 'Vitamines & suppléments'), ('OPHTALMO', 'Ophtalmologie'), ('ANTISEPTIQUES', 'Antiseptiques & désinfection'), ('MATERIEL', 'Matériel médical'), ('AUTRE', 'Autres')], default='AUTRE', max_length=20),
        ),
        migrations.AddField(
            model_name='medication',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='PatientPharmacyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=30, unique=True)),
                ('statut', models.CharField(choices=[('SOUMISE', 'Soumise'), ('EN_PREPARATION', 'En préparation'), ('PRETE', 'Prête au retrait'), ('RETIREE', 'Retirée'), ('ANNULEE', 'Annulée')], default='SOUMISE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_pharmacie', to='clinical.patient')),
            ],
            options={
                'verbose_name': 'Demande pharmacie patient',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientPharmacyRequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='pharmacy.patientpharmacyrequest')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacy.medication')),
            ],
            options={
                'verbose_name': 'Ligne demande pharmacie',
            },
        ),
    ]
