import api from './client.js'
import { downloadAuthenticated } from '../utils/download.js'

export const patientApi = {
  establishment: () => api.get('/etablissement'),
  profile: () => api.get('/patient/moi'),
  dashboard: () => api.get('/patient/tableau-de-bord'),
  appointments: () => api.get('/patient/rendez-vous'),
  cancelAppointment: (id) => api.delete(`/patient/rendez-vous/${id}`),
  bookAppointment: (data) => api.post('/rendez-vous', data),
  busySlots: (medecinId, jour) => api.get(`/medecins/${medecinId}/creneaux`, { params: { jour } }),
  medecins: () => api.get('/medecins/disponibles'),
  consultations: () => api.get('/patient/dossier/consultations'),
  documents: (patientId) => api.get(`/documents/${patientId}`),
  carePlan: () => api.get('/patient/plan-soins'),
  reminders: () => api.get('/patient/rappels-medicaments'),
  createReminder: (data) => api.post('/patient/rappels-medicaments', data),
  updateReminder: (id, data) => api.patch(`/patient/rappels-medicaments/${id}`, data),
  deleteReminder: (id) => api.delete(`/patient/rappels-medicaments/${id}`),
  labResults: () => api.get('/patient/resultats-labo'),
  conversations: () => api.get('/patient/conversations'),
  startConversation: (medecinId) => api.post(`/patient/conversations/${medecinId}`),
  messages: (convId) => api.get(`/patient/conversations/${convId}/messages`),
  sendMessage: (convId, contenu) => api.post(`/patient/conversations/${convId}/messages`, { contenu }),
  invoices: () => api.get('/patient/factures'),
  invoice: (id) => api.get(`/patient/factures/${id}`),
  initMobileMoney: (id, data) => api.post(`/patient/factures/${id}/mobile-money/initier`, data),
  confirmMobileMoney: (id, data) => api.post(`/patient/factures/${id}/mobile-money/confirmer`, data),
  approveMobileMoney: (txId, data) => api.post(`/patient/mobile-money/${txId}/approuver`, data),
  mobileMoneyStatus: (txId) => api.get(`/patient/mobile-money/${txId}/statut`),
  pharmacyCatalog: (params) => api.get('/patient/pharmacie/medicaments', { params }),
  pharmacyRequests: () => api.get('/patient/pharmacie/demandes'),
  submitPharmacyRequest: (data) => api.post('/patient/pharmacie/demandes', data),
  downloadCardPdf: () => downloadAuthenticated('/patient/carte-pdf', 'carte-patient.pdf'),
  qrCardData: (token) => api.get(`/carte-patient/${token}`),
}
