# Generated by Django 5.2.14 on 2026-06-12 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disponible_rdv',
            field=models.BooleanField(default=True, help_text='Médecin disponible pour consultations et RDV'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to='staff_photos/%Y/%m/'),
        ),
    ]
