# Generated by Django 5.2.14 on 2026-06-24 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_photo_disponibilite'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginMfaChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('code', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Défi MFA connexion',
                'ordering': ['-created_at'],
            },
        ),
    ]
